### ISSUE TITLE
Redirect from community.elgg.org to elgg.org

### ISSUE THREAD

**Issue by nlybe** [Elgg/community#12]
Another issue of elgg.org, which existed before the redesign, is that there are plenty of links to https://community.elgg.org/, which doesn't not respond any more. These links are around the Internet or even inside the this site (e.g. https://elgg.org/about/supporters)

So a permanent redirect to web server settings from community.elgg.org to elgg.org should help a lot.

**Comment by jeabakker** [comment]
I believe i have this issue fixed. I tried some old links to plugins which where on community.elgg.org. I now get redirected to elgg.org on the correct page

**Comment by nlybe** [comment]
Yes, it has been fixed now. But this issue existed when I opened this thread
